// Code generated by go generate; DO NOT EDIT.

// Package newcmmathbook provides the "NewCMMath Book" TrueType font
// from the New Computer Modern font family.
package newcmmathbook // import "github.com/rickykimani/go-newcm/newcmmathbook"

import _ "embed"

// Font is the data for the "NewCMMath Book" TrueType font.
//
//go:embed NewCMMath-Book.otf
var Font []byte
