// Code generated by go generate; DO NOT EDIT.

// Package newcmsansmathregular provides the "NewCMSansMath Regular" TrueType font
// from the New Computer Modern font family.
package newcmsansmathregular // import "github.com/rickykimani/go-newcm/newcmsansmathregular"

import _ "embed"

// Font is the data for the "NewCMSansMath Regular" TrueType font.
//
//go:embed NewCMSansMath-Regular.otf
var Font []byte
