// Code generated by go generate; DO NOT EDIT.

// Package newcm10devanagariregular provides the "NewCM10Devanagari Regular" TrueType font
// from the New Computer Modern font family.
package newcm10devanagariregular // import "github.com/rickykimani/go-newcm/newcm10devanagariregular"

import _ "embed"

// Font is the data for the "NewCM10Devanagari Regular" TrueType font.
//
//go:embed NewCM10Devanagari-Regular.otf
var Font []byte
