// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10bold provides the "NewCMMono10 Bold" TrueType font
// from the New Computer Modern font family.
package newcmmono10bold // import "github.com/rickykimani/go-newcm/newcmmono10bold"

import _ "embed"

// Font is the data for the "NewCMMono10 Bold" TrueType font.
//
//go:embed NewCMMono10-Bold.otf
var Font []byte
