// Code generated by go generate; DO NOT EDIT.

// Package newcm10bookitalic provides the "NewCM10 BookItalic" TrueType font
// from the New Computer Modern font family.
package newcm10bookitalic // import "github.com/rickykimani/go-newcm/newcm10bookitalic"

import _ "embed"

// Font is the data for the "NewCM10 BookItalic" TrueType font.
//
//go:embed NewCM10-BookItalic.otf
var Font []byte
