// Code generated by go generate; DO NOT EDIT.

// Package newcm08bookitalic provides the "NewCM08 BookItalic" TrueType font
// from the New Computer Modern font family.
package newcm08bookitalic // import "github.com/rickykimani/go-newcm/newcm08bookitalic"

import _ "embed"

// Font is the data for the "NewCM08 BookItalic" TrueType font.
//
//go:embed NewCM08-BookItalic.otf
var Font []byte
