// Code generated by go generate; DO NOT EDIT.

// Package newcmsans08bookoblique provides the "NewCMSans08 BookOblique" TrueType font
// from the New Computer Modern font family.
package newcmsans08bookoblique // import "github.com/rickykimani/go-newcm/newcmsans08bookoblique"

import _ "embed"

// Font is the data for the "NewCMSans08 BookOblique" TrueType font.
//
//go:embed NewCMSans08-BookOblique.otf
var Font []byte
