// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10oblique provides the "NewCMSans10 Oblique" TrueType font
// from the New Computer Modern font family.
package newcmsans10oblique // import "github.com/rickykimani/go-newcm/newcmsans10oblique"

import _ "embed"

// Font is the data for the "NewCMSans10 Oblique" TrueType font.
//
//go:embed NewCMSans10-Oblique.otf
var Font []byte
