// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10regular provides the "NewCMMono10 Regular" TrueType font
// from the New Computer Modern font family.
package newcmmono10regular // import "github.com/rickykimani/go-newcm/newcmmono10regular"

import _ "embed"

// Font is the data for the "NewCMMono10 Regular" TrueType font.
//
//go:embed NewCMMono10-Regular.otf
var Font []byte
