// Code generated by go generate; DO NOT EDIT.

// Package newcmsans08book provides the "NewCMSans08 Book" TrueType font
// from the New Computer Modern font family.
package newcmsans08book // import "github.com/rickykimani/go-newcm/newcmsans08book"

import _ "embed"

// Font is the data for the "NewCMSans08 Book" TrueType font.
//
//go:embed NewCMSans08-Book.otf
var Font []byte
