// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10bookoblique provides the "NewCMSans10 BookOblique" TrueType font
// from the New Computer Modern font family.
package newcmsans10bookoblique // import "github.com/rickykimani/go-newcm/newcmsans10bookoblique"

import _ "embed"

// Font is the data for the "NewCMSans10 BookOblique" TrueType font.
//
//go:embed NewCMSans10-BookOblique.otf
var Font []byte
