// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10regular provides the "NewCMSans10 Regular" TrueType font
// from the New Computer Modern font family.
package newcmsans10regular // import "github.com/rickykimani/go-newcm/newcmsans10regular"

import _ "embed"

// Font is the data for the "NewCMSans10 Regular" TrueType font.
//
//go:embed NewCMSans10-Regular.otf
var Font []byte
