// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10book provides the "NewCMMono10 Book" TrueType font
// from the New Computer Modern font family.
package newcmmono10book // import "github.com/rickykimani/go-newcm/newcmmono10book"

import _ "embed"

// Font is the data for the "NewCMMono10 Book" TrueType font.
//
//go:embed NewCMMono10-Book.otf
var Font []byte
