// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10boldoblique provides the "NewCMMono10 BoldOblique" TrueType font
// from the New Computer Modern font family.
package newcmmono10boldoblique // import "github.com/rickykimani/go-newcm/newcmmono10boldoblique"

import _ "embed"

// Font is the data for the "NewCMMono10 BoldOblique" TrueType font.
//
//go:embed NewCMMono10-BoldOblique.otf
var Font []byte
