// Code generated by go generate; DO NOT EDIT.

// Package newcm08devanagaribook provides the "NewCM08Devanagari Book" TrueType font
// from the New Computer Modern font family.
package newcm08devanagaribook // import "github.com/rickykimani/go-newcm/newcm08devanagaribook"

import _ "embed"

// Font is the data for the "NewCM08Devanagari Book" TrueType font.
//
//go:embed NewCM08Devanagari-Book.otf
var Font []byte
