// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial08bold provides the "NewCMUncial08 Bold" TrueType font
// from the New Computer Modern font family.
package newcmuncial08bold // import "github.com/rickykimani/go-newcm/newcmuncial08bold"

import _ "embed"

// Font is the data for the "NewCMUncial08 Bold" TrueType font.
//
//go:embed NewCMUncial08-Bold.otf
var Font []byte
