// Code generated by go generate; DO NOT EDIT.

// Package newcm08book provides the "NewCM08 Book" TrueType font
// from the New Computer Modern font family.
package newcm08book // import "github.com/rickykimani/go-newcm/newcm08book"

import _ "embed"

// Font is the data for the "NewCM08 Book" TrueType font.
//
//go:embed NewCM08-Book.otf
var Font []byte
