// Code generated by go generate; DO NOT EDIT.

// Package newcm10devanagaribold provides the "NewCM10Devanagari Bold" TrueType font
// from the New Computer Modern font family.
package newcm10devanagaribold // import "github.com/rickykimani/go-newcm/newcm10devanagaribold"

import _ "embed"

// Font is the data for the "NewCM10Devanagari Bold" TrueType font.
//
//go:embed NewCM10Devanagari-Bold.otf
var Font []byte
