// Code generated by go generate; DO NOT EDIT.

// Package newcm10bold provides the "NewCM10 Bold" TrueType font
// from the New Computer Modern font family.
package newcm10bold // import "github.com/rickykimani/go-newcm/newcm10bold"

import _ "embed"

// Font is the data for the "NewCM10 Bold" TrueType font.
//
//go:embed NewCM10-Bold.otf
var Font []byte
