// Code generated by go generate; DO NOT EDIT.

// Package newcm10book provides the "NewCM10 Book" TrueType font
// from the New Computer Modern font family.
package newcm10book // import "github.com/rickykimani/go-newcm/newcm10book"

import _ "embed"

// Font is the data for the "NewCM10 Book" TrueType font.
//
//go:embed NewCM10-Book.otf
var Font []byte
