// Code generated by go generate; DO NOT EDIT.

// Package newcmmathregular provides the "NewCMMath Regular" TrueType font
// from the New Computer Modern font family.
package newcmmathregular // import "github.com/rickykimani/go-newcm/newcmmathregular"

import _ "embed"

// Font is the data for the "NewCMMath Regular" TrueType font.
//
//go:embed NewCMMath-Regular.otf
var Font []byte
