// Code generated by go generate; DO NOT EDIT.

// Package newcm10devanagaribook provides the "NewCM10Devanagari Book" TrueType font
// from the New Computer Modern font family.
package newcm10devanagaribook // import "github.com/rickykimani/go-newcm/newcm10devanagaribook"

import _ "embed"

// Font is the data for the "NewCM10Devanagari Book" TrueType font.
//
//go:embed NewCM10Devanagari-Book.otf
var Font []byte
