// Code generated by go generate; DO NOT EDIT.

// Package newcm08devanagariregular provides the "NewCM08Devanagari Regular" TrueType font
// from the New Computer Modern font family.
package newcm08devanagariregular // import "github.com/rickykimani/go-newcm/newcm08devanagariregular"

import _ "embed"

// Font is the data for the "NewCM08Devanagari Regular" TrueType font.
//
//go:embed NewCM08Devanagari-Regular.otf
var Font []byte
