// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial10bold provides the "NewCMUncial10 Bold" TrueType font
// from the New Computer Modern font family.
package newcmuncial10bold // import "github.com/rickykimani/go-newcm/newcmuncial10bold"

import _ "embed"

// Font is the data for the "NewCMUncial10 Bold" TrueType font.
//
//go:embed NewCMUncial10-Bold.otf
var Font []byte
