// Code generated by go generate; DO NOT EDIT.

// Package newcm10regular provides the "NewCM10 Regular" TrueType font
// from the New Computer Modern font family.
package newcm10regular // import "github.com/rickykimani/go-newcm/newcm10regular"

import _ "embed"

// Font is the data for the "NewCM10 Regular" TrueType font.
//
//go:embed NewCM10-Regular.otf
var Font []byte
