// Code generated by go generate; DO NOT EDIT.

// Package newcm08italic provides the "NewCM08 Italic" TrueType font
// from the New Computer Modern font family.
package newcm08italic // import "github.com/rickykimani/go-newcm/newcm08italic"

import _ "embed"

// Font is the data for the "NewCM08 Italic" TrueType font.
//
//go:embed NewCM08-Italic.otf
var Font []byte
