// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10italic provides the "NewCMMono10 Italic" TrueType font
// from the New Computer Modern font family.
package newcmmono10italic // import "github.com/rickykimani/go-newcm/newcmmono10italic"

import _ "embed"

// Font is the data for the "NewCMMono10 Italic" TrueType font.
//
//go:embed NewCMMono10-Italic.otf
var Font []byte
