// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10boldoblique provides the "NewCMSans10 BoldOblique" TrueType font
// from the New Computer Modern font family.
package newcmsans10boldoblique // import "github.com/rickykimani/go-newcm/newcmsans10boldoblique"

import _ "embed"

// Font is the data for the "NewCMSans10 BoldOblique" TrueType font.
//
//go:embed NewCMSans10-BoldOblique.otf
var Font []byte
