// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial10book provides the "NewCMUncial10 Book" TrueType font
// from the New Computer Modern font family.
package newcmuncial10book // import "github.com/rickykimani/go-newcm/newcmuncial10book"

import _ "embed"

// Font is the data for the "NewCMUncial10 Book" TrueType font.
//
//go:embed NewCMUncial10-Book.otf
var Font []byte
