// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial08book provides the "NewCMUncial08 Book" TrueType font
// from the New Computer Modern font family.
package newcmuncial08book // import "github.com/rickykimani/go-newcm/newcmuncial08book"

import _ "embed"

// Font is the data for the "NewCMUncial08 Book" TrueType font.
//
//go:embed NewCMUncial08-Book.otf
var Font []byte
