// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10bold provides the "NewCMSans10 Bold" TrueType font
// from the New Computer Modern font family.
package newcmsans10bold // import "github.com/rickykimani/go-newcm/newcmsans10bold"

import _ "embed"

// Font is the data for the "NewCMSans10 Bold" TrueType font.
//
//go:embed NewCMSans10-Bold.otf
var Font []byte
