// Code generated by go generate; DO NOT EDIT.

// Package newcm08regular provides the "NewCM08 Regular" TrueType font
// from the New Computer Modern font family.
package newcm08regular // import "github.com/rickykimani/go-newcm/newcm08regular"

import _ "embed"

// Font is the data for the "NewCM08 Regular" TrueType font.
//
//go:embed NewCM08-Regular.otf
var Font []byte
