// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial10regular provides the "NewCMUncial10 Regular" TrueType font
// from the New Computer Modern font family.
package newcmuncial10regular // import "github.com/rickykimani/go-newcm/newcmuncial10regular"

import _ "embed"

// Font is the data for the "NewCMUncial10 Regular" TrueType font.
//
//go:embed NewCMUncial10-Regular.otf
var Font []byte
