// Code generated by go generate; DO NOT EDIT.

// Package newcm10italic provides the "NewCM10 Italic" TrueType font
// from the New Computer Modern font family.
package newcm10italic // import "github.com/rickykimani/go-newcm/newcm10italic"

import _ "embed"

// Font is the data for the "NewCM10 Italic" TrueType font.
//
//go:embed NewCM10-Italic.otf
var Font []byte
