// Code generated by go generate; DO NOT EDIT.

// Package newcmsans08regular provides the "NewCMSans08 Regular" TrueType font
// from the New Computer Modern font family.
package newcmsans08regular // import "github.com/rickykimani/go-newcm/newcmsans08regular"

import _ "embed"

// Font is the data for the "NewCMSans08 Regular" TrueType font.
//
//go:embed NewCMSans08-Regular.otf
var Font []byte
