// Code generated by go generate; DO NOT EDIT.

// Package newcmsans10book provides the "NewCMSans10 Book" TrueType font
// from the New Computer Modern font family.
package newcmsans10book // import "github.com/rickykimani/go-newcm/newcmsans10book"

import _ "embed"

// Font is the data for the "NewCMSans10 Book" TrueType font.
//
//go:embed NewCMSans10-Book.otf
var Font []byte
