// Code generated by go generate; DO NOT EDIT.

// Package newcmsans08oblique provides the "NewCMSans08 Oblique" TrueType font
// from the New Computer Modern font family.
package newcmsans08oblique // import "github.com/rickykimani/go-newcm/newcmsans08oblique"

import _ "embed"

// Font is the data for the "NewCMSans08 Oblique" TrueType font.
//
//go:embed NewCMSans08-Oblique.otf
var Font []byte
