// Code generated by go generate; DO NOT EDIT.

// Package newcmmathbold provides the "NewCMMath Bold" TrueType font
// from the New Computer Modern font family.
package newcmmathbold // import "github.com/rickykimani/go-newcm/newcmmathbold"

import _ "embed"

// Font is the data for the "NewCMMath Bold" TrueType font.
//
//go:embed NewCMMath-Bold.otf
var Font []byte
