// Code generated by go generate; DO NOT EDIT.

// Package newcm10bolditalic provides the "NewCM10 BoldItalic" TrueType font
// from the New Computer Modern font family.
package newcm10bolditalic // import "github.com/rickykimani/go-newcm/newcm10bolditalic"

import _ "embed"

// Font is the data for the "NewCM10 BoldItalic" TrueType font.
//
//go:embed NewCM10-BoldItalic.otf
var Font []byte
