// Code generated by go generate; DO NOT EDIT.

// Package newcmuncial08regular provides the "NewCMUncial08 Regular" TrueType font
// from the New Computer Modern font family.
package newcmuncial08regular // import "github.com/rickykimani/go-newcm/newcmuncial08regular"

import _ "embed"

// Font is the data for the "NewCMUncial08 Regular" TrueType font.
//
//go:embed NewCMUncial08-Regular.otf
var Font []byte
