// Code generated by go generate; DO NOT EDIT.

// Package newcmmono10bookitalic provides the "NewCMMono10 BookItalic" TrueType font
// from the New Computer Modern font family.
package newcmmono10bookitalic // import "github.com/rickykimani/go-newcm/newcmmono10bookitalic"

import _ "embed"

// Font is the data for the "NewCMMono10 BookItalic" TrueType font.
//
//go:embed NewCMMono10-BookItalic.otf
var Font []byte
